version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "rewindio/devops"
    labels:
      - "appsec"
    open-pull-requests-limit: 10
