name: checkov
concurrency: checkov

on: [pull_request, workflow_call]

permissions: read-all

jobs:
  checkov-static-analysis:
    name: "checkov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Checkov static analysis
        id: static-analysis
        uses: bridgecrewio/checkov-action@d0e41abbcc8c1103c6ae7e451681d071f05e1c20 # v12.2873.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: cli
