name: checkov
concurrency: checkov

on: [pull_request, workflow_call]

permissions: read-all

jobs:
  checkov-static-analysis:
    name: "checkov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Checkov static analysis
        id: static-analysis
        uses: bridgecrewio/checkov-action@74b041188934dbffda9ae5b7ab0032856388e0fb # v12.2539.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: cli
