name: checkov
concurrency: checkov

on: [pull_request, workflow_call]

permissions: read-all

jobs:
  checkov-static-analysis:
    name: "checkov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Checkov static analysis
        id: static-analysis
        uses: bridgecrewio/checkov-action@96706fc4e79ab92bb5b6f336bf0f559845e2449d # v12.2533.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: cli
