name: checkov
concurrency: checkov

on: [pull_request, workflow_call]

permissions: read-all

jobs:
  checkov-static-analysis:
    name: "checkov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Checkov static analysis
        id: static-analysis
        uses: bridgecrewio/checkov-action@9bbf36a57da8688ee2fd4221773f0345646bad6d # v12.2531.0
        with:
          directory: .
          framework: terraform
          hard_fail_on: CRITICAL
          skip_check: CKV_TF_1
          output_format: cli
